// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package querytest

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Record struct {
	ID        int64
	TenantID  int64
	Name      string
	Age       int32
	Status    string
	CreatedAt pgtype.Timestamptz
}
