// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dynamicquerysqlite

import (
	"context"
	"strings"
	"time"
)

const createRecord = `-- name: CreateRecord :exec
INSERT INTO records (tenant_id, name, age, status)
VALUES (?1, ?2, ?3, ?4)
`

type CreateRecordParams struct {
	TenantID int64
	Name     string
	Age      int64
	Status   string
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) error {
	_, err := q.db.ExecContext(ctx, createRecord,
		arg.TenantID,
		arg.Name,
		arg.Age,
		arg.Status,
	)
	return err
}

const excludeContacts = `-- name: ExcludeContacts :many
SELECT id, name, age, status, created_at FROM records
WHERE tenant_id = ?1
`

type ExcludeContactsRow struct {
	ID        int64
	Name      string
	Age       int64
	Status    string
	CreatedAt time.Time
}

type ExcludeContactsOpts struct {
	name    *string
	status  *string
	orderBy []string
}

func (o ExcludeContactsOpts) Name(v string) ExcludeContactsOpts {
	o.name = &v
	return o
}

func (o ExcludeContactsOpts) Status(v string) ExcludeContactsOpts {
	o.status = &v
	return o
}
func (q *Queries) ExcludeContacts(ctx context.Context, tenantID int64, opts ExcludeContactsOpts) ([]ExcludeContactsRow, error) {
	query := excludeContacts
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 2)
	n := 1
	_ = n
	g0 := make([]string, 0, 1)
	if opts.name != nil {
		g0 = append(g0, "name = ?")
		queryParams = append(queryParams, *opts.name)
	}
	switch len(g0) {
	case 0:
	case 1:
		conds = append(conds, "NOT ("+g0[0]+")")
	default:
		conds = append(conds, "NOT "+"("+strings.Join(g0, " AND ")+")")
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExcludeContactsRow
	for rows.Next() {
		var i ExcludeContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterRecords = `-- name: FilterRecords :many
SELECT id, name, age, created_at FROM records
WHERE tenant_id = ?1
`

type FilterRecordsRow struct {
	ID        int64
	Name      string
	Age       int64
	CreatedAt time.Time
}

type FilterRecordsOpts struct {
	ids     []int64
	orderBy []string
}

func (o FilterRecordsOpts) Ids(v []int64) FilterRecordsOpts {
	o.ids = v
	return o
}
func (q *Queries) FilterRecords(ctx context.Context, tenantID int64, opts FilterRecordsOpts) ([]FilterRecordsRow, error) {
	query := filterRecords
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 1)
	n := 1
	_ = n
	if len(opts.ids) > 0 {
		ph := make([]string, len(opts.ids))
		for i, v := range opts.ids {
			ph[i] = "?"
			queryParams = append(queryParams, v)
		}
		conds = append(conds, "id IN ("+strings.Join(ph, ", ")+")")
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterRecordsRow
	for rows.Next() {
		var i FilterRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT id, name, age, created_at FROM records
WHERE tenant_id = ?1
`

type ListRecordsRow struct {
	ID        int64
	Name      string
	Age       int64
	CreatedAt time.Time
}

type ListRecordsOpts struct {
	name    *string
	age     *int64
	orderBy []string
}

func (o ListRecordsOpts) Name(v string) ListRecordsOpts {
	o.name = &v
	return o
}

func (o ListRecordsOpts) Age(v int64) ListRecordsOpts {
	o.age = &v
	return o
}

type ListRecordsOrderByColumn string

const (
	ListRecordsOrderByName      ListRecordsOrderByColumn = "name"
	ListRecordsOrderByAge       ListRecordsOrderByColumn = "age"
	ListRecordsOrderByCreatedAt ListRecordsOrderByColumn = "created_at"
)

func (o ListRecordsOpts) OrderBy(col ListRecordsOrderByColumn, desc bool) ListRecordsOpts {
	dir := " ASC"
	if desc {
		dir = " DESC"
	}
	o.orderBy = append(o.orderBy, string(col)+dir)
	return o
}
func (q *Queries) ListRecords(ctx context.Context, tenantID int64, opts ListRecordsOpts) ([]ListRecordsRow, error) {
	query := listRecords
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 2)
	n := 1
	_ = n
	if opts.name != nil {
		conds = append(conds, "name = ?")
		queryParams = append(queryParams, *opts.name)
	}
	if opts.age != nil {
		conds = append(conds, "age = ?")
		queryParams = append(queryParams, *opts.age)
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordsRow
	for rows.Next() {
		var i ListRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContacts = `-- name: SearchContacts :many
SELECT id, name, age, status, created_at FROM records
WHERE tenant_id = ?1
`

type SearchContactsRow struct {
	ID        int64
	Name      string
	Age       int64
	Status    string
	CreatedAt time.Time
}

type SearchContactsOpts struct {
	name    *string
	status  *string
	orderBy []string
}

func (o SearchContactsOpts) Name(v string) SearchContactsOpts {
	o.name = &v
	return o
}

func (o SearchContactsOpts) Status(v string) SearchContactsOpts {
	o.status = &v
	return o
}
func (q *Queries) SearchContacts(ctx context.Context, tenantID int64, opts SearchContactsOpts) ([]SearchContactsRow, error) {
	query := searchContacts
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 2)
	n := 1
	_ = n
	if opts.name != nil {
		conds = append(conds, "name = ?")
		queryParams = append(queryParams, *opts.name)
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchContactsRow
	for rows.Next() {
		var i SearchContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
