// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"time"
)

const listRecords = `-- name: ListRecords :many
SELECT id, name, age, created_at FROM records
WHERE tenant_id = $1
`

type ListRecordsParams struct {
	TenantID int64
	Name     string
	Age      int32
}

type ListRecordsRow struct {
	ID        int64
	Name      string
	Age       int32
	CreatedAt time.Time
}

// @dynamic name eq
// @dynamic age gt
// @dynamic-sort name, age, created_at
func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]ListRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecords, arg.TenantID, arg.Name, arg.Age)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordsRow
	for rows.Next() {
		var i ListRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
