// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package querytest

import (
	"context"
	"fmt"
	"strings"
	"time"
)

const getRecord = `-- name: GetRecord :one
SELECT id, name, age, created_at FROM records
WHERE tenant_id = $1
`

type GetRecordRow struct {
	ID        int64
	Name      string
	Age       int32
	CreatedAt time.Time
}

type GetRecordOpts struct {
	name    *string
	age     *int32
	orderBy []string
}

func (o GetRecordOpts) Name(v string) GetRecordOpts {
	o.name = &v
	return o
}

func (o GetRecordOpts) Age(v int32) GetRecordOpts {
	o.age = &v
	return o
}

// GetRecord returns a single tenant record, optionally narrowed by an exact
// name and a minimum age. QueryRow yields the first matching row.
func (q *Queries) GetRecord(ctx context.Context, tenantID int64, opts GetRecordOpts) (GetRecordRow, error) {
	query := getRecord
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 2)
	n := 1
	_ = n
	if opts.name != nil {
		n++
		conds = append(conds, fmt.Sprintf("name = $%d", n))
		queryParams = append(queryParams, *opts.name)
	}
	if opts.age != nil {
		n++
		conds = append(conds, fmt.Sprintf("age >= $%d", n))
		queryParams = append(queryParams, *opts.age)
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var i GetRecordRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Age,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRecords = `-- name: ListActiveRecords :many
SELECT id, name, age, status, created_at FROM records
WHERE tenant_id = $1
  AND status = $2
`

type ListActiveRecordsParams struct {
	TenantID int64
	Status   string
}

type ListActiveRecordsRow struct {
	ID        int64
	Name      string
	Age       int32
	Status    string
	CreatedAt time.Time
}

type ListActiveRecordsOpts struct {
	name    *string
	age     *int32
	orderBy []string
}

func (o ListActiveRecordsOpts) Name(v string) ListActiveRecordsOpts {
	o.name = &v
	return o
}

func (o ListActiveRecordsOpts) Age(v int32) ListActiveRecordsOpts {
	o.age = &v
	return o
}

type ListActiveRecordsOrderByColumn string

const (
	ListActiveRecordsOrderByName      ListActiveRecordsOrderByColumn = "name"
	ListActiveRecordsOrderByAge       ListActiveRecordsOrderByColumn = "age"
	ListActiveRecordsOrderByCreatedAt ListActiveRecordsOrderByColumn = "created_at"
)

func (o ListActiveRecordsOpts) OrderBy(col ListActiveRecordsOrderByColumn, desc bool) ListActiveRecordsOpts {
	dir := " ASC"
	if desc {
		dir = " DESC"
	}
	o.orderBy = append(o.orderBy, string(col)+dir)
	return o
}

// ListActiveRecords returns a tenant's records for a given status, optionally
// narrowed by an exact name and a minimum age, and optionally ordered.
func (q *Queries) ListActiveRecords(ctx context.Context, arg ListActiveRecordsParams, opts ListActiveRecordsOpts) ([]ListActiveRecordsRow, error) {
	query := listActiveRecords
	queryParams := []interface{}{arg.TenantID, arg.Status}
	conds := make([]string, 0, 2)
	n := 2
	_ = n
	if opts.name != nil {
		n++
		conds = append(conds, fmt.Sprintf("name = $%d", n))
		queryParams = append(queryParams, *opts.name)
	}
	if opts.age != nil {
		n++
		conds = append(conds, fmt.Sprintf("age >= $%d", n))
		queryParams = append(queryParams, *opts.age)
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRecordsRow
	for rows.Next() {
		var i ListActiveRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT id, name, age, created_at FROM records
WHERE tenant_id = $1
`

type ListRecordsRow struct {
	ID        int64
	Name      string
	Age       int32
	CreatedAt time.Time
}

type ListRecordsOpts struct {
	name    *string
	age     *int32
	orderBy []string
}

func (o ListRecordsOpts) Name(v string) ListRecordsOpts {
	o.name = &v
	return o
}

func (o ListRecordsOpts) Age(v int32) ListRecordsOpts {
	o.age = &v
	return o
}

type ListRecordsOrderByColumn string

const (
	ListRecordsOrderByName      ListRecordsOrderByColumn = "name"
	ListRecordsOrderByAge       ListRecordsOrderByColumn = "age"
	ListRecordsOrderByCreatedAt ListRecordsOrderByColumn = "created_at"
)

func (o ListRecordsOpts) OrderBy(col ListRecordsOrderByColumn, desc bool) ListRecordsOpts {
	dir := " ASC"
	if desc {
		dir = " DESC"
	}
	o.orderBy = append(o.orderBy, string(col)+dir)
	return o
}
func (q *Queries) ListRecords(ctx context.Context, tenantID int64, opts ListRecordsOpts) ([]ListRecordsRow, error) {
	query := listRecords
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 2)
	n := 1
	_ = n
	if opts.name != nil {
		n++
		conds = append(conds, fmt.Sprintf("name = $%d", n))
		queryParams = append(queryParams, *opts.name)
	}
	if opts.age != nil {
		n++
		conds = append(conds, fmt.Sprintf("age > $%d", n))
		queryParams = append(queryParams, *opts.age)
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordsRow
	for rows.Next() {
		var i ListRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
