// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dynamicquerypgx

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecord = `-- name: CreateRecord :exec
INSERT INTO records (tenant_id, name, age, status)
VALUES ($1, $2, $3, $4)
`

type CreateRecordParams struct {
	TenantID int64
	Name     string
	Age      int32
	Status   string
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) error {
	_, err := q.db.Exec(ctx, createRecord,
		arg.TenantID,
		arg.Name,
		arg.Age,
		arg.Status,
	)
	return err
}

const excludeContacts = `-- name: ExcludeContacts :many
SELECT id, name, age, status, created_at FROM records
WHERE tenant_id = $1
`

type ExcludeContactsRow struct {
	ID        int64
	Name      string
	Age       int32
	Status    string
	CreatedAt pgtype.Timestamptz
}

type ExcludeContactsOpts struct {
	name    *string
	status  *string
	orderBy []string
}

func (o ExcludeContactsOpts) Name(v string) ExcludeContactsOpts {
	o.name = &v
	return o
}

func (o ExcludeContactsOpts) Status(v string) ExcludeContactsOpts {
	o.status = &v
	return o
}

func (q *Queries) ExcludeContacts(ctx context.Context, tenantID int64, opts ExcludeContactsOpts) ([]ExcludeContactsRow, error) {
	query := excludeContacts
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 2)
	n := 1
	_ = n
	g0 := make([]string, 0, 1)
	g1 := make([]string, 0, 2)
	if opts.name != nil {
		n++
		g1 = append(g1, fmt.Sprintf("name = $%d", n))
		queryParams = append(queryParams, *opts.name)
	}
	if opts.status != nil {
		n++
		g1 = append(g1, fmt.Sprintf("status = $%d", n))
		queryParams = append(queryParams, *opts.status)
	}
	switch len(g1) {
	case 0:
	case 1:
		g0 = append(g0, g1[0])
	default:
		g0 = append(g0, "("+strings.Join(g1, " OR ")+")")
	}
	switch len(g0) {
	case 0:
	case 1:
		conds = append(conds, "NOT ("+g0[0]+")")
	default:
		conds = append(conds, "NOT "+"("+strings.Join(g0, " AND ")+")")
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.Query(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExcludeContactsRow
	for rows.Next() {
		var i ExcludeContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterRecords = `-- name: FilterRecords :many
SELECT id, name, age, created_at FROM records
WHERE tenant_id = $1
`

type FilterRecordsRow struct {
	ID        int64
	Name      string
	Age       int32
	CreatedAt pgtype.Timestamptz
}

type FilterRecordsOpts struct {
	ids     []int64
	orderBy []string
}

func (o FilterRecordsOpts) Ids(v []int64) FilterRecordsOpts {
	o.ids = v
	return o
}

func (q *Queries) FilterRecords(ctx context.Context, tenantID int64, opts FilterRecordsOpts) ([]FilterRecordsRow, error) {
	query := filterRecords
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 1)
	n := 1
	_ = n
	if len(opts.ids) > 0 {
		ph := make([]string, len(opts.ids))
		for i, v := range opts.ids {
			n++
			ph[i] = fmt.Sprintf("$%d", n)
			queryParams = append(queryParams, v)
		}
		conds = append(conds, "id IN ("+strings.Join(ph, ", ")+")")
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.Query(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterRecordsRow
	for rows.Next() {
		var i FilterRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecord = `-- name: GetRecord :one
SELECT id, name, age, created_at FROM records
WHERE tenant_id = $1
`

type GetRecordRow struct {
	ID        int64
	Name      string
	Age       int32
	CreatedAt pgtype.Timestamptz
}

type GetRecordOpts struct {
	name    *string
	age     *int32
	orderBy []string
}

func (o GetRecordOpts) Name(v string) GetRecordOpts {
	o.name = &v
	return o
}

func (o GetRecordOpts) Age(v int32) GetRecordOpts {
	o.age = &v
	return o
}

type GetRecordOrderByColumn string

const (
	GetRecordOrderByName      GetRecordOrderByColumn = "name"
	GetRecordOrderByAge       GetRecordOrderByColumn = "age"
	GetRecordOrderByCreatedAt GetRecordOrderByColumn = "created_at"
)

func (o GetRecordOpts) OrderBy(col GetRecordOrderByColumn, desc bool) GetRecordOpts {
	dir := " ASC"
	if desc {
		dir = " DESC"
	}
	o.orderBy = append(o.orderBy, string(col)+dir)
	return o
}

// GetRecord returns a single tenant record, optionally narrowed by an exact
// name and a minimum age, and optionally ordered. QueryRow yields the first
// matching row (order it to make "first" deterministic).
func (q *Queries) GetRecord(ctx context.Context, tenantID int64, opts GetRecordOpts) (GetRecordRow, error) {
	query := getRecord
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 2)
	n := 1
	_ = n
	if opts.name != nil {
		n++
		conds = append(conds, fmt.Sprintf("name = $%d", n))
		queryParams = append(queryParams, *opts.name)
	}
	if opts.age != nil {
		n++
		conds = append(conds, fmt.Sprintf("age >= $%d", n))
		queryParams = append(queryParams, *opts.age)
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	row := q.db.QueryRow(ctx, query, queryParams...)
	var i GetRecordRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Age,
		&i.CreatedAt,
	)
	return i, err
}

const getRecordIn = `-- name: GetRecordIn :one
SELECT id, name, age, created_at FROM records
WHERE tenant_id = $1
`

type GetRecordInRow struct {
	ID        int64
	Name      string
	Age       int32
	CreatedAt pgtype.Timestamptz
}

type GetRecordInOpts struct {
	ids     []int64
	orderBy []string
}

func (o GetRecordInOpts) Ids(v []int64) GetRecordInOpts {
	o.ids = v
	return o
}

type GetRecordInOrderByColumn string

const (
	GetRecordInOrderByID GetRecordInOrderByColumn = "id"
)

func (o GetRecordInOpts) OrderBy(col GetRecordInOrderByColumn, desc bool) GetRecordInOpts {
	dir := " ASC"
	if desc {
		dir = " DESC"
	}
	o.orderBy = append(o.orderBy, string(col)+dir)
	return o
}

// GetRecordIn returns the first tenant record whose id is in an optional set,
// exercising sqlc.slice IN-expansion on the single-row path. Order it to make
// "first" deterministic.
func (q *Queries) GetRecordIn(ctx context.Context, tenantID int64, opts GetRecordInOpts) (GetRecordInRow, error) {
	query := getRecordIn
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 1)
	n := 1
	_ = n
	if len(opts.ids) > 0 {
		ph := make([]string, len(opts.ids))
		for i, v := range opts.ids {
			n++
			ph[i] = fmt.Sprintf("$%d", n)
			queryParams = append(queryParams, v)
		}
		conds = append(conds, "id IN ("+strings.Join(ph, ", ")+")")
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	row := q.db.QueryRow(ctx, query, queryParams...)
	var i GetRecordInRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Age,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRecords = `-- name: ListActiveRecords :many
SELECT id, name, age, status, created_at FROM records
WHERE tenant_id = $1
  AND status = $2
`

type ListActiveRecordsParams struct {
	TenantID int64
	Status   string
}

type ListActiveRecordsRow struct {
	ID        int64
	Name      string
	Age       int32
	Status    string
	CreatedAt pgtype.Timestamptz
}

type ListActiveRecordsOpts struct {
	name    *string
	age     *int32
	orderBy []string
}

func (o ListActiveRecordsOpts) Name(v string) ListActiveRecordsOpts {
	o.name = &v
	return o
}

func (o ListActiveRecordsOpts) Age(v int32) ListActiveRecordsOpts {
	o.age = &v
	return o
}

type ListActiveRecordsOrderByColumn string

const (
	ListActiveRecordsOrderByName      ListActiveRecordsOrderByColumn = "name"
	ListActiveRecordsOrderByAge       ListActiveRecordsOrderByColumn = "age"
	ListActiveRecordsOrderByCreatedAt ListActiveRecordsOrderByColumn = "created_at"
)

func (o ListActiveRecordsOpts) OrderBy(col ListActiveRecordsOrderByColumn, desc bool) ListActiveRecordsOpts {
	dir := " ASC"
	if desc {
		dir = " DESC"
	}
	o.orderBy = append(o.orderBy, string(col)+dir)
	return o
}

// ListActiveRecords returns a tenant's records for a given status, optionally
// narrowed by an exact name and a minimum age, and optionally ordered.
func (q *Queries) ListActiveRecords(ctx context.Context, arg ListActiveRecordsParams, opts ListActiveRecordsOpts) ([]ListActiveRecordsRow, error) {
	query := listActiveRecords
	queryParams := []interface{}{arg.TenantID, arg.Status}
	conds := make([]string, 0, 2)
	n := 2
	_ = n
	if opts.name != nil {
		n++
		conds = append(conds, fmt.Sprintf("name = $%d", n))
		queryParams = append(queryParams, *opts.name)
	}
	if opts.age != nil {
		n++
		conds = append(conds, fmt.Sprintf("age >= $%d", n))
		queryParams = append(queryParams, *opts.age)
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.Query(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveRecordsRow
	for rows.Next() {
		var i ListActiveRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT id, name, age, created_at FROM records
WHERE tenant_id = $1
`

type ListRecordsRow struct {
	ID        int64
	Name      string
	Age       int32
	CreatedAt pgtype.Timestamptz
}

type ListRecordsOpts struct {
	name    *string
	age     *int32
	orderBy []string
}

func (o ListRecordsOpts) Name(v string) ListRecordsOpts {
	o.name = &v
	return o
}

func (o ListRecordsOpts) Age(v int32) ListRecordsOpts {
	o.age = &v
	return o
}

type ListRecordsOrderByColumn string

const (
	ListRecordsOrderByName      ListRecordsOrderByColumn = "name"
	ListRecordsOrderByAge       ListRecordsOrderByColumn = "age"
	ListRecordsOrderByCreatedAt ListRecordsOrderByColumn = "created_at"
)

func (o ListRecordsOpts) OrderBy(col ListRecordsOrderByColumn, desc bool) ListRecordsOpts {
	dir := " ASC"
	if desc {
		dir = " DESC"
	}
	o.orderBy = append(o.orderBy, string(col)+dir)
	return o
}

func (q *Queries) ListRecords(ctx context.Context, tenantID int64, opts ListRecordsOpts) ([]ListRecordsRow, error) {
	query := listRecords
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 2)
	n := 1
	_ = n
	if opts.name != nil {
		n++
		conds = append(conds, fmt.Sprintf("name = $%d", n))
		queryParams = append(queryParams, *opts.name)
	}
	if opts.age != nil {
		n++
		conds = append(conds, fmt.Sprintf("age > $%d", n))
		queryParams = append(queryParams, *opts.age)
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.Query(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordsRow
	for rows.Next() {
		var i ListRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContacts = `-- name: SearchContacts :many
SELECT id, name, age, status, created_at FROM records
WHERE tenant_id = $1
`

type SearchContactsRow struct {
	ID        int64
	Name      string
	Age       int32
	Status    string
	CreatedAt pgtype.Timestamptz
}

type SearchContactsOpts struct {
	name    *string
	status  *string
	orderBy []string
}

func (o SearchContactsOpts) Name(v string) SearchContactsOpts {
	o.name = &v
	return o
}

func (o SearchContactsOpts) Status(v string) SearchContactsOpts {
	o.status = &v
	return o
}

func (q *Queries) SearchContacts(ctx context.Context, tenantID int64, opts SearchContactsOpts) ([]SearchContactsRow, error) {
	query := searchContacts
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 2)
	n := 1
	_ = n
	g0 := make([]string, 0, 2)
	if opts.name != nil {
		n++
		g0 = append(g0, fmt.Sprintf("name = $%d", n))
		queryParams = append(queryParams, *opts.name)
	}
	if opts.status != nil {
		n++
		g0 = append(g0, fmt.Sprintf("status = $%d", n))
		queryParams = append(queryParams, *opts.status)
	}
	switch len(g0) {
	case 0:
	case 1:
		conds = append(conds, g0[0])
	default:
		conds = append(conds, "("+strings.Join(g0, " OR ")+")")
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.Query(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchContactsRow
	for rows.Next() {
		var i SearchContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecords = `-- name: SearchRecords :many
SELECT id, name, age, created_at FROM records
WHERE tenant_id = $1
`

type SearchRecordsRow struct {
	ID        int64
	Name      string
	Age       int32
	CreatedAt pgtype.Timestamptz
}

type SearchRecordsOpts struct {
	pattern *string
	orderBy []string
}

func (o SearchRecordsOpts) Pattern(v string) SearchRecordsOpts {
	o.pattern = &v
	return o
}

func (q *Queries) SearchRecords(ctx context.Context, tenantID int64, opts SearchRecordsOpts) ([]SearchRecordsRow, error) {
	query := searchRecords
	queryParams := []interface{}{tenantID}
	conds := make([]string, 0, 1)
	n := 1
	_ = n
	if opts.pattern != nil {
		n++
		conds = append(conds, fmt.Sprintf("name LIKE $%d", n))
		queryParams = append(queryParams, *opts.pattern)
	}
	if len(conds) > 0 {
		query += " AND " + strings.Join(conds, " AND ")
	}
	if len(opts.orderBy) > 0 {
		query += " ORDER BY " + strings.Join(opts.orderBy, ", ")
	}
	rows, err := q.db.Query(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchRecordsRow
	for rows.Next() {
		var i SearchRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Age,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
